@echo off
chcp 65001 >nul
REM ============================================================
REM HMOL Launcher Clean Script (v2.2)
REM ============================================================
REM
REM Removes temporary files, build artifacts, and unused
REM files generated by the application and build process.
REM
REM Usage:
REM   clean.bat                    Default clean (artifacts + cache + test logs)
REM   clean.bat --all              All clean (default + app logs + IDE cache)
REM   clean.bat --deep             Deep clean (--all + user data, requires confirm)
REM   clean.bat --logs             Only clean application logs
REM   clean.bat --dry-run          Preview mode (no actual deletion)
REM   clean.bat --nopause          No pause before exit (for CI)
REM   clean.bat --help             Show help
REM
REM Protected (NEVER deleted):
REM   - HMOL_qt.py, crypto_utils.py, anti_debug.py
REM   - input_validation.py, rate_limiter.py, security_audit.py
REM   - obfuscate.py, cleanup_temp.py
REM   - HMOL_config.json, msal_token_cache.enc
REM   - icon.ico
REM   - All .py source files
REM   - All .md documentation
REM   - LICENSE, README.md, EULA.md
REM   - .gitignore, .env.example
REM
REM ============================================================

setlocal enabledelayedexpansion

cd /d "%~dp0"

set "MODE=default"
set "DRY_RUN=0"
set "NO_PAUSE=0"

:parse_args
if "%~1"=="" goto :end_parse
if /i "%~1"=="--all"       set "MODE=all"      & shift & goto :parse_args
if /i "%~1"=="--deep"      set "MODE=deep"     & shift & goto :parse_args
if /i "%~1"=="--logs"      set "MODE=logs"     & shift & goto :parse_args
if /i "%~1"=="--dry-run"   set "DRY_RUN=1"     & shift & goto :parse_args
if /i "%~1"=="--nopause"   set "NO_PAUSE=1"    & shift & goto :parse_args
if /i "%~1"=="--help"      goto :show_help
if /i "%~1"=="-h"          goto :show_help
if /i "%~1"=="--version"   goto :show_version
echo [WARN] Unknown option: %~1
shift
goto :parse_args
:end_parse

echo.
echo ============================================================
echo   HMOL Launcher Clean Script v2.2
echo ============================================================
echo   Mode: %MODE%
if "%DRY_RUN%"=="1" echo   [DRY-RUN MODE] No files will be deleted
echo.

set "FILES_DELETED=0"
set "DIRS_DELETED=0"
set "BYTES_FREED=0"
set "SKIPPED=0"
set "ERRORS=0"
set "PROTECTED=0"

goto :main

:count_size
if not exist "%~1" goto :count_size_end
for %%A in ("%~1") do set /a "BYTES_FREED+=%%~zA"
goto :count_size_end
:count_size_end
exit /b 0

:delete_file
if not exist "%~1" goto :delete_file_end
if "%DRY_RUN%"=="1" (
    echo   [DRY] Would delete: %~1
    set /a "FILES_DELETED+=1"
    goto :delete_file_end
)
call :count_size "%~1"
del /F /Q "%~1" >nul 2>&1
if errorlevel 1 (
    echo   [ERROR] Failed to delete: %~1
    set /a "ERRORS+=1"
) else (
    echo   [DEL] %~1
    set /a "FILES_DELETED+=1"
)
:delete_file_end
exit /b 0

:delete_dir
if not exist "%~1" goto :delete_dir_end
if "%DRY_RUN%"=="1" (
    echo   [DRY] Would delete directory: %~1
    set /a "DIRS_DELETED+=1"
    goto :delete_dir_end
)
rmdir /S /Q "%~1" >nul 2>&1
if errorlevel 1 (
    echo   [ERROR] Failed to delete directory: %~1
    set /a "ERRORS+=1"
) else (
    echo   [DEL] %~1\
    set /a "DIRS_DELETED+=1"
)
:delete_dir_end
exit /b 0

:is_protected
set "PROTECTED_PATTERN=HMOL_qt.py crypto_utils.py anti_debug.py input_validation.py rate_limiter.py security_audit.py obfuscate.py cleanup_temp.py HMOL_config.json msal_token_cache.enc icon.ico LICENSE README.md EULA.md SECURITY_CHECKLIST.md CLEANUP_USAGE.md .gitignore .env.example build.bat build_enhanced.bat clean.bat test_clean.bat"
set "IS_PROTECTED=0"
for %%P in (%PROTECTED_PATTERN%) do (
    if /i "%~1"=="%%P" set "IS_PROTECTED=1"
)
exit /b 0

:main

echo ============================================================
echo [1/8] Cleaning PyInstaller build artifacts...
echo ============================================================
call :delete_dir "build"
call :delete_dir "dist"
if exist "*.spec" (
    for %%S in (*.spec) do (
        call :is_protected "%%S"
        if "!IS_PROTECTED!"=="1" (
            echo   [PROTECTED] Skipping: %%S
            set /a "PROTECTED+=1"
        ) else (
            call :delete_file "%%S"
        )
    )
)

echo.
echo ============================================================
echo [2/8] Cleaning Python bytecode cache...
echo ============================================================
for /d /r . %%D in (__pycache__) do (
    if exist "%%D" call :delete_dir "%%D"
)
if exist "*.pyc" del /F /S /Q "*.pyc" >nul 2>&1
if exist "*.pyo" del /F /S /Q "*.pyo" >nul 2>&1
if exist "*.pyd" del /F /S /Q "*.pyd" >nul 2>&1
for /d /r . %%E in (*.egg-info) do (
    if exist "%%E" call :delete_dir "%%E"
)

echo.
echo ============================================================
echo [3/8] Cleaning test logs and debug files...
echo ============================================================
for %%F in (test_*.log test_*.txt debug_*.log debug_*.txt *.pytest.log audit_report.txt security_test_results.log final_test.log) do (
    if exist "%%F" call :delete_file "%%F"
)

echo.
echo ============================================================
echo [4/8] Cleaning temporary files...
echo ============================================================
for %%F in (*.tmp *.bak *.old *~) do (
    if exist "%%F" call :delete_file "%%F"
)
if exist "mo_manager_config.json.legacy.bak" call :delete_file "mo_manager_config.json.legacy.bak"

echo.
echo ============================================================
echo [5/8] Cleaning OS junk files...
echo ============================================================
for %%F in (Thumbs.db .DS_Store desktop.ini ehthumbs.db ehthumbs_vista.db) do (
    if exist "%%F" call :delete_file "%%F"
)
for /r . %%F in (Thumbs.db .DS_Store desktop.ini) do (
    if exist "%%F" call :delete_file "%%F"
)

echo.
echo ============================================================
echo [6/8] Cleaning root-level .exe files (build artifacts)...
echo ============================================================
if exist "*.exe" (
    for %%E in (*.exe) do (
        call :is_protected "%%E"
        if "!IS_PROTECTED!"=="1" (
            echo   [PROTECTED] Skipping: %%E
            set /a "PROTECTED+=1"
        ) else (
            call :delete_file "%%E"
        )
    )
)
for %%F in (*.msi *.app *.dmg *.deb *.rpm *.pkg) do (
    if exist "%%F" call :delete_file "%%F"
)

echo.
echo ============================================================
echo [7/8] Cleaning additional artifacts (--all)...
echo ============================================================
if /i "%MODE%"=="all" goto :clean_all
if /i "%MODE%"=="deep" goto :clean_all
if /i "%MODE%"=="logs" goto :clean_logs_only
goto :clean_skip_extended

:clean_logs_only
echo   [INFO] Cleaning application logs only...
if exist "logs" (
    for %%F in (logs\HMOL_*.log logs\*.txt) do (
        if exist "%%F" call :delete_file "%%F"
    )
)
goto :clean_skip_extended

:clean_all
echo   [INFO] Mode: ALL - Cleaning application logs + IDE cache...
if exist "logs" (
    for %%F in (logs\HMOL_*.log logs\*.txt) do (
        if exist "%%F" call :delete_file "%%F"
    )
)
if exist "logs" (
    dir /b "logs\*.*" >nul 2>&1
    if errorlevel 1 call :delete_dir "logs"
)
if exist ".vscode" call :delete_dir ".vscode"
if exist ".idea" call :delete_dir ".idea"
for %%F in (*.swp *.swo) do (
    if exist "%%F" call :delete_file "%%F"
)
if exist "audit_*.log" (
    for %%F in (audit_*.log) do (
        if exist "%%F" call :delete_file "%%F"
    )
)
if /i "%MODE%"=="deep" goto :clean_deep
goto :clean_skip_extended

:clean_deep
echo.
echo ============================================================
echo [DEEP] Cleaning sensitive files (REQUIRES CONFIRMATION)...
echo ============================================================
echo   [WARN] Deep mode will delete:
echo     - msal_token_cache.enc  (MSAL token cache, encrypted)
echo.
echo   [!] WARNING:
echo       Deleting msal_token_cache.enc will require re-authentication
echo       of Microsoft account on next launch.
echo.
if "%DRY_RUN%"=="1" (
    echo   [DRY-RUN] Skipping confirmation in dry-run mode
    goto :clean_skip_extended
)
set /p "CONFIRM=Type 'YES I UNDERSTAND' to continue: "
if not "!CONFIRM!"=="YES I UNDERSTAND" (
    echo   [ABORT] Deep clean cancelled
    goto :clean_skip_extended
)
if exist "msal_token_cache.enc" call :delete_file "msal_token_cache.enc"

:clean_skip_extended

echo.
echo ============================================================
echo [8/8] Summary
echo ============================================================
echo.
if "%DRY_RUN%"=="1" (
    echo   [DRY-RUN] No files were actually deleted
    echo.
)
echo   Files deleted:       %FILES_DELETED%
echo   Directories deleted: %DIRS_DELETED%
echo   Bytes freed:         %BYTES_FREED% (~%BYTES_FREED% bytes)
echo   Protected (skipped): %PROTECTED%
echo   Errors:              %ERRORS%
echo.
echo ============================================================
echo   Clean complete!
echo ============================================================
echo.
echo ============================================================
echo   Clean SUCCEEDED!
echo ============================================================
echo   If dist\ still exists, it is locked by another process
echo   (e.g. HMOL.exe running, or a file explorer window open).
echo   Close it and re-run clean.bat if needed.
echo ============================================================
echo.

echo.
echo ============================================================
echo Verifying critical files are intact...
echo ============================================================
set "MISSING=0"
set "CHECK_LIST=HMOL_qt.py crypto_utils.py anti_debug.py input_validation.py rate_limiter.py security_audit.py obfuscate.py cleanup_temp.py icon.ico LICENSE README.md EULA.md"
for %%F in (%CHECK_LIST%) do (
    if exist "%%F" (
        echo   [OK] %%F
    ) else (
        echo   [CRITICAL] Missing: %%F
        set /a "MISSING+=1"
    )
)
if "%MISSING%"=="0" (
    echo.
    echo   All critical files are intact.
) else (
    echo.
    echo   [ERROR] %MISSING% critical files are missing!
)

echo.

if "%NO_PAUSE%"=="1" exit /b 0
if "%DRY_RUN%"=="1" (
    echo Press any key to exit...
    pause >nul
) else (
    echo Press any key to exit...
    pause >nul
)
endlocal
exit /b 0

:show_help
echo.
echo HMOL Launcher Clean Script v2.2
echo.
echo USAGE:
echo   clean.bat [options]
echo.
echo OPTIONS:
echo   (no args)       Default clean: build artifacts, Python cache, test logs, temp files, .exe
echo   --all           Also clean: application logs, IDE cache
echo   --deep          Also clean: msal_token_cache.enc (DANGEROUS - requires re-auth)
echo   --logs          Only clean application logs in logs\
echo   --dry-run       Preview what would be deleted, no actual changes
echo   --nopause       Don't pause before exit (for CI/CD)
echo   --help, -h      Show this help message
echo   --version       Show version information
echo.
echo EXAMPLES:
echo   clean.bat                    # Standard cleanup
echo   clean.bat --all --dry-run    # Preview full cleanup
echo   clean.bat --deep             # Clean including sensitive files
echo   clean.bat --nopause          # For CI/CD pipelines
echo.
echo PROTECTED FILES (NEVER DELETED):
echo   - HMOL_qt.py                 (main launcher)
echo   - crypto_utils.py            (encryption)
echo   - anti_debug.py              (anti-tamper)
echo   - input_validation.py        (security)
echo   - rate_limiter.py            (security)
echo   - security_audit.py          (audit)
echo   - obfuscate.py               (obfuscation)
echo   - cleanup_temp.py            (this cleanup tool)
echo   - HMOL_config.json           (user configuration)
echo   - icon.ico                   (program icon)
echo   - All .py source files
echo   - All .md documentation
echo   - LICENSE, README.md, EULA.md
echo   - .gitignore, .env.example
echo.
endlocal
exit /b 0

:show_version
echo.
echo HMOL Launcher Clean Script
echo Version: 2.2
echo Build Date: 2026-07-17
echo.
echo Compatible with: HMOL Launcher v2.2.x
echo Python: 3.10+
echo Platform: Windows 10/11
echo.
endlocal
exit /b 0
