name: All Contributors Auto

on:
  # 当有 issue 或 pull request 被创建、评论时触发
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  all-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: All Contributors Auto Action
        uses: JoshuaKGoldberg/all-contributors-auto-action@v0.6.1
